query GetPokemon($no: Int, $locales: [Int!]) {
  pokemon(where: { id: { _eq: $no } }) {
    id
    height
    weight
    pokemonspecy {
      id
      has_gender_differences
      gender_rate
      pokemonspeciesnames(where: { language_id: { _in: $locales } }) {
        id
        genus
        language_id
        name
      }
      pokemonspeciesflavortexts(where: { language_id: { _in: $locales } }) {
        id
        flavor_text
        language_id
        version {
          id
          name
        }
      }
      evolutionchain {
        id
        pokemonspecies(order_by: { id: asc }) {
          id
          evolves_from_species_id
          pokemonspeciesnames(where: { language_id: { _in: $locales } }) {
            id
            language_id
            name
          }
          pokemonevolutions {
            id
            min_affection
            min_beauty
            min_happiness
            min_level
            time_of_day
            relative_physical_stats
            turn_upside_down
            needs_overworld_rain
            item {
              id
              itemnames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
            location {
              id
              locationnames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
              region {
                id
                regionnames(where: { language_id: { _in: $locales } }) {
                  id
                  language_id
                  name
                }
              }
            }
            gender {
              id
              name
            }
            evolutiontrigger {
              id
              name
            }
            PokemonspecyByPartySpeciesId {
              id
              pokemonspeciesnames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
            PokemonspecyByTradeSpeciesId {
              id
              pokemonspeciesnames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
            ItemByHeldItemId {
              id
              itemnames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
            move {
              id
              movenames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
              type {
                id
                typenames(where: { language_id: { _in: $locales } }) {
                  id
                  language_id
                  name
                }
              }
            }
            TypeByPartyTypeId {
              id
              typenames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
            type {
              id
              typenames(where: { language_id: { _in: $locales } }) {
                id
                language_id
                name
              }
            }
          }
        }
      }
    }
    pokemontypes(order_by: { id: asc }) {
      id
      type {
        id
        typenames(where: { language_id: { _in: $locales } }) {
          id
          name
          language_id
        }
        TypeefficaciesByTargetTypeId(order_by: { target_type_id: asc }) {
          id
          damage_factor
          type {
            id
            typenames(where: { language_id: { _in: $locales } }) {
              id
              name
              language_id
            }
          }
        }
      }
    }
    pokemonmoves(order_by: { move_id: asc }, distinct_on: [move_id]) {
      id
      level
      move {
        id
        accuracy
        pp
        priority
        power
        movenames(where: { language_id: { _in: $locales } }) {
          id
          name
          language_id
        }
        movedamageclass {
          id
          name
        }
        movemeta {
          id
          ailment_chance
          crit_rate
          drain
          flinch_chance
          healing
          max_hits
          max_turns
          min_hits
          min_turns
          stat_chance
          movemetaailment {
            id
            name
          }
          movemetacategory {
            id
            name
          }
        }
        type {
          id
          typenames(where: { language_id: { _in: $locales } }) {
            id
            name
            language_id
          }
        }
      }
    }
    pokemonabilities {
      id
      ability {
        abilitynames(where: { language_id: { _in: $locales } }) {
          id
          name
          language_id
        }
        abilityflavortexts(where: { language_id: { _in: $locales } }) {
          id
          flavor_text
          language_id
        }
      }
    }
  }
  pokemon_aggregate(where: { is_default: { _eq: true } }) {
    aggregate {
      count(distinct: true, columns: id)
    }
  }
}
