query GetPokemons($locales: [Int!]) {
  pokemon(
    order_by: { id: asc }
    where: { is_default: { _eq: true } }
  ) {
    id
    pokemonsprites {
      id
      sprites
    }
    pokemonspecy {
      id
      pokemonspeciesnames(
        where: { language_id: { _in: $locales } }
      ) {
        id
        language_id
        name
      }
    }
    pokemontypes {
      id
      type {
        id
        name
      }
    }
  }
  typename(where: { language_id: { _in: $locales } }) {
    id
    language_id
    name
    type_id
  }
}
